### PR TITLE
[WIP] Export functionality

### PR DESCRIPTION
**Pull request by chrismytton**
This is code from @ajparsons that I didn't want to get lost in a branch!

### CODE REVIEW

**Comment by ajparsons** [comment]
@chrismytton : I'm having a go at tidying up the commit history on this and getting tests in for new features today (and merging in the new features since Dec) - so I wouldn't worry about this branch for the moment (soon, hopefully!).

**Comment by andylolz** [comment]
Would it be a nightmare to split the refactor out from the new feature? (Possibly just as part of the commit history tidy up?) If so, don’t worry too much!

**Comment by ajparsons** [comment]
@andylolz : That's the current plan! (as far as I can, given the refactor is in part to make the new feature much easier)

**Comment by ajparsons** [comment]
Pull request #17 now deals with the nicer version of this branch - fine to close this request.

**Comment by mhl** [comment]
I'm closing this as suggested.

**Pull request closed without merging**
